cart/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

computer_store/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from shop.views import Search

urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n/", include('django.conf.urls.i18n'))
]

urlpatterns += i18n_patterns (
    path('', TemplateView.as_view(template_name="home.html"), name="home"),
    path('users/', include('users.urls')),
    path('catalog/', include(('shop.urls', 'shop'), namespace='shop')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('coupons/', include(('coupons.urls', 'coupons'), namespace='coupons')),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

coupons/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

orders/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shop/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('search/', views.Search.as_view(), name='search'),
    path('<slug:slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

coupons/forms.py
from django import forms


class CouponApplyForm(forms.Form):
    code = forms.CharField()

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                            initial={'quantity': item['quantity'],
                            'update': True})
    coupon_apply_form = CouponApplyForm()
    return render(request,
                  'cart/detail.html',
                  {'cart': cart,
                   'coupon_apply_form': coupon_apply_form})

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static i18n %}

{% block meta %}
    {% if not user.is_authenticated %}
        <meta http-equiv="refresh" content="0.1;URL=/">
    {% endif %}
{% endblock %}

{% block title %}
    {% trans 'Your shopping cart' %}
{% endblock %}

{% block style_css %}
    <link rel="stylesheet" href="{% static 'cart/css/cart_detail.css' %}">
{% endblock %}

{% block content %}
    <h1 style="display: flex; justify-content: center; margin-bottom: 20px">{% trans 'Your shopping cart' %}</h1>
    <table class="table table-striped align-middle cart" id="table">
        <thead>
        <tr>
            <th class="col-md-2">{% trans 'Image' %}</th>
            <th class="col-md-2">{% trans 'Product' %}</th>
            <th class="col-md-2">{% trans 'Quantity' %}</th>
            <th class="col-md-2">{% trans 'Unit price' %}</th>
            <th class="col-md-2">{% trans 'Price' %}</th>
            <th class="col-md-2"></th>
        </tr>
        </thead>

        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td class="col-md-2">
                        <a href="{{ product.get_absolute_url }}">
                            <img class="table-image" src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static "shop/img/no_image.png" %}
                                {% endif %}">
                        </a>
                    </td>
                    <td class="col-md-2">
                        <a href="{{ product.get_absolute_url }}">
                            {{ product.name }}
                        </a>
                    </td>
                    <td class="col-md-2">
                        {{ item.quantity }}
                    </td>
                    <td class="col-md-2">
                        {{ item.price }} BYN
                    </td>
                    <td class="col-md-2">
                        {{ item.total_price }} BYN
                    </td>
                    <td class="col-md-2">
                        <a href="{% url "cart:cart_remove" product.id %} " style="color: red">{% trans 'Remove' %}</a>
                    </td>
                </tr>
            {% endwith %}

        {% empty %}
            <tr>
                <td class="col-md-12 text-center" colspan="6">
                    {% trans 'NO items to display' %}
                </td>
            </tr>
        {% endfor %}

        {% if cart.coupon %}
            <tr class="subtotal">
                <td colspan="4"></td>
                <td style="font-weight: 540; font-size: 16px">{% trans 'Subtotal' %}</td>
                <td class="num">{{ cart.get_total_price }} BYN</td>
            </tr>
            <tr>
                <td colspan="4"></td>
                <td>
                    {% trans 'coupon' %} "<span style="font-weight: 520; font-size: 16px">{{ cart.coupon.code }}</span>" <br>
                    ({{ cart.coupon.discount }}%)
                </td>
                <td class="num neg">
                    - {{ cart.get_discount|floatformat:"2" }} BYN
                </td>
            </tr>
        {% endif %}

        <tr class="total">
            <td colspan="4"></td>
            <td style="font-weight: 600; font-size: 18px">{% trans 'Total' %}</td>
            <td class="num">{{ cart.get_total_price_after_discount|floatformat:"2" }} BYN</td>
        </tr>
        </tbody>
    </table>

    <div class="coupon">
        <form action="{% url "coupons:apply" %}" method="post">{% csrf_token %}
            <div class="input-group mb-3">
                <label for="id_code" class="input-group-text" style="font-size: 20px; line-height: 18px">{% trans 'Code' %}: </label>
                <input type="text" class="form-control" name="code" required="" id="id_code"
                       aria-describedby="button-addon2">
                <button type="submit" class="btn btn-outline-secondary btn-coupon" id="button-addon2">✓</button>
            </div>
        </form>
    </div>


    <p class="text-center" style="margin-top: 20px">
        <a href="{% url "shop:product_list" %}" class="btn btn2" style="margin-right: 10px">
            {% trans "Continue shopping" %}
        </a>
        {% if cart.get_total_price != 0 %}
            <a href="{% url "orders:order_create" %}" class="btn btn2" style="padding-top: 15px">
                {% trans "Checkout" %}
            </a>
        {% endif %}
    </p>
{% endblock %}