cart/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

computer_store/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from shop.views import Search

urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n/", include('django.conf.urls.i18n'))
]

urlpatterns += i18n_patterns (
    path('', TemplateView.as_view(template_name="home.html"), name="home"),
    path('users/', include('users.urls')),
    path('catalog/', include(('shop.urls', 'shop'), namespace='shop')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('coupons/', include(('coupons.urls', 'coupons'), namespace='coupons')),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('search/', views.Search.as_view(), name='search'),
    path('<slug:slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

shop/models.py
import datetime

from django.db import models
from users.models import User
from django.urls import reverse



class Category(models.Model):
    name = models.CharField(max_length=50, db_index=True)
    slug = models.SlugField(max_length=60, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class PhoneDetails(models.Model):
    model = models.CharField(max_length=100, default='')
    display = models.TextField()
    processor = models.TextField()
    size_and_weight = models.TextField()
    camera = models.TextField()
    video = models.TextField()
    front_cam = models.TextField()
    mobile_cnct = models.TextField()
    os = models.CharField(max_length=25, default='')

    class Meta:
        ordering = ('model',)
        verbose_name = 'Детали телефона'
        verbose_name_plural = 'Детали телефонов'

    def __str__(self):
        return self.model


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(default='slug', max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(default=datetime.datetime.now())
    updated = models.DateTimeField(default=datetime.datetime.now())
    memory = models.CharField(max_length=10, default='0GB')
    ram = models.CharField(max_length=10, default='0GB')
    ph_color_hex = models.CharField(max_length=50, default='')
    ph_color_name = models.CharField(max_length=50, default='')
    details = models.ForeignKey(PhoneDetails, on_delete=models.CASCADE)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Телефон'
        verbose_name_plural = 'Телефоны'
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])


class PhoneConfiguration(models.Model):
    phone_id = models.ForeignKey(Product, related_name='configuration', on_delete=models.CASCADE)
    phone_configurations = models.ManyToManyField(Product, related_name='Configurations')

    class Meta:
        verbose_name = 'Конфигурация'
        verbose_name_plural = 'Конфигурации телефонов'

    def __str__(self):
        return self.phone_id.name


class PhoneColors(models.Model):
    phone_id = models.ForeignKey(Product, related_name='color', on_delete=models.CASCADE)
    phone_colors = models.ManyToManyField(Product, related_name='Colors')

    class Meta:
        verbose_name = 'Цвет'
        verbose_name_plural = 'Цвета телефонов'

    def __str__(self):
        return self.phone_id.name

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from django.core.paginator import Paginator
from django.urls import reverse_lazy

from .models import Category, Product, PhoneConfiguration, PhoneColors
from cart.forms import CartAddProductForm


def product_list(request, slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    colors = Product.objects.order_by('ph_color_hex').values_list('ph_color_hex', 'ph_color_name_en').distinct()
    memory = Product.objects.order_by('details__product__memory').values_list('details__product__memory', flat=True).distinct()
    cart_product_form = CartAddProductForm()
    if slug:
        if slug == 'android' or slug == 'iOS':
            category = get_object_or_404(Category, slug=slug)
            products = products.filter(category=category)
        elif slug[0].isnumeric():
            products = products.filter(memory=slug)
        else:
            products = products.filter(ph_color_name_en=slug)

    paginator = Paginator(products, 9)
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)

    return render(request, template_name='shop/product/list.html',
                  context={'category': category,
                           'categories': categories,
                           'products': products,
                           'cart_product_form': cart_product_form,
                           'colors': colors,
                           'memory': memory})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug, )

    phone_configs = PhoneConfiguration.objects.filter(phone_id=id)[0].phone_configurations.all()
    phone_colors = PhoneColors.objects.filter(phone_id=id)[0].phone_colors.all()

    product.details.display = product.details.display.split(';')
    product.details.camera = product.details.camera.split(';')
    product.details.front_cam = product.details.front_cam.split(';')
    product.details.processor = product.details.processor.split(';')
    product.details.size_and_weight = product.details.size_and_weight.split(';')
    product.details.video = product.details.video.split(';')
    product.details.mobile_cnct = product.details.mobile_cnct.split(';')

    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form,
                                                        'phone_configs': phone_configs,
                                                        'phone_colors': phone_colors,
                                                        'range': range(1, product.stock + 1)})


class Search(ListView):
    template_name = 'shop/product/list.html'
    context_object_name = 'products'

    def get_queryset(self):
        return Product.objects.filter(name__icontains=self.request.GET.get("q"))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = self.request.GET.get("q")
        context['categories'] = Category.objects.all()
        return context

shop/templates/shop/product/detail.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}

{% block style_css %}
    <link rel="stylesheet" href="{% static 'shop/css/product_detail.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="wrapper">
            <div class="wrapper-left">
                <div class="wrapper-image-main">
                    <img alt="{{ product.name }}"
                         src="{% if product.image %}{{ product.image.url }}{% else %}{% static "shop/img/no_image.png" %}{% endif %}"
                    >
                </div>
            </div>

            <div class="wrapper-right">
                <h1 style="text-align: center;">{{ product.name }}</h1>
                <div class="product-details">
                    <p class="product-brand">{% trans 'Brand' %}: <span>{{ product.category }}</span></p>

                    <p class="product-title-text">{% trans 'Memory Size' %}</p>
                    <div class="product-block">
                        {% for config in phone_configs %}
                            <div class="product-memory-link">
                                <a href="{{ config.get_absolute_url }}"
                                   style="text-decoration: none; color: #fff;">
                                    {{ config.memory }}
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                    <p class="product-title-text">{% trans 'Colors' %}</p>
                    <div class="product-block">
                        {% for phone_color in phone_colors %}
                            <form action="{{ phone_color.get_absolute_url }}">
                                <button class="btn btn-color" title="{{ phone_color.ph_color_name }}"
                                        style="background-color: {{ phone_color.ph_color_hex }} "></button>
                            </form>
                        {% endfor %}
                    </div>

                    <p class="product-price"> {{ product.price }} BYN </p>
                    <form class="input-group" style="width: 300px" action="{% url "cart:cart_add" product.id %}"
                          method="post">
                        {#                        <label class="product-title-text" for="id_quantity">{% trans 'Quantity' %}:</label>#}
                        <select class="form-select" name="quantity" id="id_quantity">
                            {% for i in range %}
                                <option value={{ i }}>{{ i }}</option>
                            {% endfor %}
                        </select>

                        {#                            {{ cart_product_form }}#}
                        {% csrf_token %}
                        <button class="btn btn-buy {% if not user.is_authenticated %} disabled {% endif %}"
                                type="submit">{% trans 'Add to cart' %}</button>
                    </form>

                </div>
            </div>
        </div>


        <div class="description">
            <h1 style="text-align: center">{% trans 'Details' %}</h1>
            <table style="width: 90%">
                <tbody>
                <tr>
                    <td style="width: 23%; font-size: 22px; font-weight: 600">{% trans 'Model' %}</td>
                    <td style="width: 235.477%;">{{ product.details.model }}</td>
                </tr>
                <tr>
                    <td style="width: 23%; font-size: 22px; font-weight: 600">{% trans 'Color' %}</td>
                    <td style="width: 235.477%;">{{ product.ph_color_name }}</td>
                </tr>
                <tr>
                    <td style="width: 23%; font-size: 22px; font-weight: 600">{% trans 'Memory Size' %}</td>
                    <td style="width: 235.477%;">{{ product.memory }}</td>
                </tr>
                <tr>
                    <td style="width: 23%; font-size: 22px; font-weight: 600">{% trans 'Display' %}</td>
                    <td style="width: 235.477%;">
                        <ul>
                            {% for item in product.details.display %}
                                <li>{{ item }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td style="width: 23%; font-size: 22px; font-weight: 600">{% trans 'Processor' %}</td>
                    <td style="width: 235.477%;">
                        <ul>
                            {% for item in product.details.processor %}
                                <li>{{ item }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td style="width: 23%; font-size: 22px; font-weight: 600">{% trans 'Size and Weight' %}</td>
                    <td style="width: 235.477%;">
                        <ul>
                            {% for item in product.details.size_and_weight %}
                                <li>{{ item }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td style="width: 23%; font-size: 22px; font-weight: 600">{% trans 'Camera' %}</td>
                    <td style="width: 235.477%;">
                        <ul>
                            {% for item in product.details.camera %}
                                <li>{{ item }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td style="width: 23%; font-size: 22px; font-weight: 600">{% trans 'Video Recording' %}</td>
                    <td style="width: 235.477%;">
                        <ul>
                            {% for item in product.details.video %}
                                <li>{{ item }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td style="width: 23%; font-size: 22px; font-weight: 600">{% trans 'Front Camera' %}</td>
                    <td style="width: 235.477%;">
                        <ul>
                            {% for item in product.details.front_cam %}
                                <li>{{ item }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td style="width: 23%; font-size: 22px; font-weight: 600">{% trans 'Cellular and Wireless' %}</td>
                    <td style="width: 235.477%;">
                        <ul>
                            {% for item in product.details.mobile_cnct %}
                                <li>{{ item }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% trans 'Products' %}{% endblock %}


{% block style_css %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'shop/css/catalog_list.css' %}">
{% endblock %}


{% block content %}
    <div class="catalogContainer" style="margin-bottom: 30px">
        <aside>
            <h3 style="display: flex; justify-content: center; margin-top: 20px"> {% trans 'Filter' %} </h3>
            <ul style="list-style-type: none">
                <li>
                    <hr class="dropdown-divider" style="margin-right: 2rem; margin-top: 20px">
                </li>
                <li class="filter">
                    <a class="filter-link" href="{% url "shop:product_list" %}">{% trans 'All' %}</a>
                </li>
                <li>
                    <hr class="dropdown-divider" style="margin-right: 2rem">
                </li>
                {% for c in categories %}
                    <li class="filter">
                        <a class="filter-link" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                {% endfor %}
                <li>
                    <hr class="dropdown-divider" style="margin-right: 2rem">
                </li>
                <p class="filter-link" style="margin-bottom: 5px">{% trans 'Colors' %}:</p>
                <ul style="list-style-type: none; padding-left: 0; margin-left: 8px; margin-right: 1.8rem;">
                    {% for hex, name in colors %}
                        <li class="filter-color">
                            <a class="btn btn-color" href="http://127.0.0.1:777/ru/catalog/{{ name }}"
                               title="{{ name }}"
                               style="background-color: {{ hex }}; border: #1d9444 solid 1px"></a>
                        </li>
                    {% endfor %}
                </ul>

                <li>
                    <hr class="dropdown-divider" style="margin-right: 2rem">
                </li>

                <p class="filter-link" style="margin-bottom: 5px">{% trans 'Memory Size' %}:</p>
                <ul style="list-style-type: none; display: flex; flex-wrap: wrap; justify-content: center; padding-left: 0; margin-top: 5px; max-width: 226px">
                    {% for mem in memory %}
                        <li class="filter-memory">
                            <a href="http://127.0.0.1:777/ru/catalog/{{ mem }}"
                               title="{{ mem }}">
                                {{ mem }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>

            </ul>
        </aside>

        <div class="catalog">
            {% for product in products %}
                <div class="product-card">
                    <div class="product-thumb">
                        <a href="{{ product.get_absolute_url }}" style="text-decoration: none;">
                            <img src="

                                    {% if product.image %}{{ product.image.url }}{% else %}{% static "shop/img/no_image.png" %}{% endif %}"
                                 alt="{{ product.name }}">
                        </a>
                    </div>
                    <div class="product-details">
                        <a href="{{ product.get_absolute_url }}" style="text-decoration: none;">
                            <h5 style="color: #1b1b1b">{{ product.name }}</h5>
                        </a>


                        <div class="product-bottom-details d-flex justify-content-between align-items-center">
                            <div class="product-price">
                                {{ product.price }} BYN
                            </div>
                            <form action="{% url "cart:cart_add" product.id %}" method="post">{% csrf_token %}
                                <div hidden="hidden">
                                    {{ cart_product_form }}
                                </div>
                                <input type="submit"
                                       class="btn btn2 {% if not user.is_authenticated %} disabled {% endif %}"
                                       value='{% trans "Add to Cart" %}'>
                            </form>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
    <nav class="page-navigation" aria-label="Page navigation">
        <ul class="pagination">
            <li class="page-item">
                {% if products.has_previous %}
                    <a class="page-link" href="?page={{ products.previous_page_number }}"
                       aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                {% else %}
                    <div class="page-link disabled"><span>&laquo;</span></div>
                {% endif %}
            </li>
            {% for i in products.paginator.page_range %}
                {% if products.number == i %}
                    <li class="active page-item"><span class="page-link">{{ i }}</span></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            <li class="page-item">
                {% if products.has_next %}
                    <a class="page-link" href="?page={{ products.next_page_number }}"
                       aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                {% else %}
                    <div class="page-link disabled"><span>&raquo;</span></div>
                {% endif %}
            </li>
        </ul>
    </nav>

{% endblock %}

{% block script %}
    <script>
        $(function () {
            $('#search-box').autocomplete({
                source: '/products/',
                minLength: 1,
                select: function (event, ui) {
                    window.location.href = '/products/' + ui.item.id;
                }
            });
        });
    </script>
{% endblock %}