cart/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

computer_store/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from shop.views import Search

urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n/", include('django.conf.urls.i18n'))
]

urlpatterns += i18n_patterns (
    path('', TemplateView.as_view(template_name="home.html"), name="home"),
    path('users/', include('users.urls')),
    path('catalog/', include(('shop.urls', 'shop'), namespace='shop')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('coupons/', include(('coupons.urls', 'coupons'), namespace='coupons')),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

orders/models.py
from django.db import models
from shop.models import Product
from users.models import User
from decimal import Decimal
from django.core.validators import MinValueValidator, MaxValueValidator
from coupons.models import Coupon


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    coupon = models.ForeignKey(Coupon, related_name='orders', null=True, blank=True, on_delete=models.CASCADE)
    discount = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        total_cost = sum(item.get_cost() for item in self.items.all())
        return total_cost - total_cost * (self.discount / Decimal('100'))


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order
from users.models import User


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

        user = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.HiddenInput())

orders/views.py
from django.shortcuts import render
from django.core.mail import send_mail

from computer_store.settings import DEFAULT_FROM_EMAIL
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart


def order_create(request):
    cart = Cart(request)

    if request.method == 'POST':
        form = OrderCreateForm(request.POST)

        if form.is_valid():
            order_request = form.save(commit=False)  # Создаем объект, но не сохраняем его в БД
            order_request.user = request.user  # Указываем пользователя в поле person

            if cart.coupon:
                order_request.coupon = cart.coupon
                order_request.discount = cart.coupon.discount

            order_request.save()

            for item in cart:
                OrderItem.objects.create(order=order_request,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # очистка корзины

            send_mail(subject='Successful Order Message',
                      message=f"""
You have successfully created an order on Телефончик.by
Total price {cart.get_total_price_after_discount()} BYN
Our experts will contact you shortly
Have a nice day!
            """,
                      recipient_list=[order_request.user.email],
                      from_email=DEFAULT_FROM_EMAIL
                      )
            cart.clear()
            return render(request, 'orders/created.html',
                          {'order': order_request})
    else:
        form = OrderCreateForm
    return render(request, 'orders/create.html',
                  {'cart': cart, 'form': form})

orders/templates/orders/create.html
{% extends "base.html" %}
{% load static i18n %}

{% block meta %}
    {% if not user.is_authenticated %}
        <meta http-equiv="refresh" content="0.1;URL=/">
    {% endif %}
{% endblock %}

{% block title %}{% trans 'Checkout' %}{% endblock %}

{% block style_css %}
    <link rel="stylesheet" href="{% static 'orders/css/create_page.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{% endblock %}

{% block content %}
    <div class="order-info">
        <p style="font-size: 38px">{% trans 'Your order' %}</p>
        <table class="table table-striped align-middle cart" id="table">
            <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td class="col-md-2">
                            <a href="{{ product.get_absolute_url }}">
                                <img class="table-image" src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static "shop/img/no_image.png" %}
                                {% endif %}">
                            </a>
                        </td>
                        <td class="col-md-3">
                            <a href="{{ product.get_absolute_url }}">
                                {{ product.name }}
                            </a>
                        </td>
                        <td class="col-md-1">
                            {{ item.quantity }}
                        </td>
                        <td class="col-md-2">
                            {{ item.price }} BYN
                        </td>
                        <td class="col-md-2">
                            {{ item.total_price }} BYN
                        </td>
                        <td class="col-md-2">
                            <a href="{% url "cart:cart_remove" product.id %} " style="color: red">{% trans 'Remove' %}</a>
                        </td>
                    </tr>
                {% endwith %}
            {% endfor %}

            <tr class="total">
                {% if cart.coupon %}
                    <td style="font-weight: 600; font-size: 18px">{% trans 'Discount' %}</td>
                    <td>"{{ cart.coupon.code }}" {{ cart.coupon.discount }}% </td>
                    <td colspan="2"></td>
                {% else %}
                    <td colspan="4"></td>
                {% endif %}

                <td style="font-weight: 600; font-size: 18px">{% trans 'Total' %}</td>
                <td class="num">{{ cart.get_total_price_after_discount|floatformat:"2" }} BYN</td>
            </tr>
            </tbody>
        </table>
    </div>


    <h1 style="text-align: center; margin-top: 50px">{% trans 'Information about You' %}</h1>
    <form action="." method="post" class="form-horizontal order-form" style="">{% csrf_token %}
        <input type="hidden" name="user" value="{{ user.pk }}">

        <div class="wrapper">
            <div class="wrapper-left">
                <div class="block-to-center">
                    <div class="form-group">
                        <label for="id_first_name">{% trans 'First Name' %}:</label>
                        <input class="form-control" type="text" name="first_name" value="{{ user.first_name }}"
                               maxlength="50"
                               required id="id_first_name" style="width: 250px">
                    </div>

                    <div class="form-group">
                        <label for="id_last_name">{% trans 'Last Name' %}:</label>
                        <input class="form-control" type="text" name="last_name" value="{{ user.last_name }}"
                               maxlength="50"
                               required id="id_last_name" style="width: 250px">
                    </div>

                    <div class="form-group">
                        <label for="id_email">Email:</label>
                        <input class="form-control" type="email" name="email" value="{{ user.email }}" maxlength="254"
                               required
                               id="id_email" style="width: 250px">
                    </div>
                </div>
            </div>

            <div class="wrapper-right">
                <div class="block-to-center">
                    <div class="form-group">
                        <label for="id_address">{% trans 'Address' %}:</label>
                        <input class="form-control" type="text" name="address" maxlength="250" required id="id_address"
                               style="width: 250px">
                    </div>

                    <div class="form-group">
                        <label for="id_postal_code">{% trans 'Postal code' %}:</label>
                        <input class="form-control" type="text" name="postal_code" maxlength="20" required
                               id="id_postal_code"
                               style="width: 250px">
                    </div>

                    <div class="form-group">
                        <label for="id_city">{% trans 'City' %}:</label>
                        <input class="form-control" type="text" name="city" maxlength="100" required id="id_city"
                               style="width: 250px">
                    </div>
                </div>
            </div>
        </div>

        <div style="text-align: center; margin-bottom: 30px">
            <input class="btn btn-buy" type="submit" value="{% trans 'Place order' %}">
        </div>
    </form>

{% endblock %}

orders/templates/orders/created.html
{% extends "base.html" %}
{% load static i18n %}

{% block meta %}
        <meta http-equiv="refresh" content="2;URL=/">
{% endblock %}

{% block title %}{% trans 'Succesful Order' %}{% endblock %}

{% block content %}
    <h1>{% trans 'Thank you' %}</h1>
    <p>{% trans 'Your order has been successfully completed. Your order number is' %}
        <strong>{{ order.id }}</strong>.</p>
    <p>{% trans 'Our experts will contact you shortly' %}</p>
    <p>{% trans 'You will be redirected in few seconds..' %}</p>
{% endblock %}